### PR TITLE
Add parameters to the disk to set read/write limits

### PR DESCRIPTION
**Pull request by V-Paranoiaque**

### CODE REVIEW

**Comment by cospeedster** [comment]
@ggongaware

**Comment by ggongaware** [comment]
Do these need to propagate through the proxmox-api-go?

**Comment by V-Paranoiaque** [comment]
No need @ggongaware the parameters are added automatically by the API

**Comment by ggongaware** [comment]
Do they populate as zeros '0' from the default and is that ok?

**Comment by V-Paranoiaque** [comment]
If the parameter is omitted the parameter is removed by the Proxmox API

**Pull request merged**
