### PR TITLE
 Update to go1.16, modules, darwin/arm64 support

### LINKED ISSUE #338: v2.6.9 Unexpected content for method DELETE
Provider version: 2.6.9
Terraform version: 0.15.1
PVE version: 6.4-4

Cannot delete an LXC during `terraform destroy`

The following is the relevant debug log chunk:

```
{"data":null}
2021/04/30 19:43:48 >>>>>>>>>> REQUEST:
DELETE /api2/json/nodes/pve1/lxc/115 HTTP/1.1
Host: 192.168.0.200:8006
User-Agent: Go-http-client/1.1
Content-Length: 2
Accept: application/json
Cookie: PVEAuthCookie=<redacted>
Accept-Encoding: gzip

""
2021/04/30 19:43:48 <<<<<<<<<< RESULT:
HTTP/1.1 501 Unexpected content for method 'DELETE'
Connection: close
Cache-Control: max-age=0
Date: Fri, 30 Apr 2021 19:43:48 GMT
Expires: Fri, 30 Apr 2021 19:43:48 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0
```

### LINKED ISSUE #339: No darwin_arm64 build available
The provider plugin currently does not support a pre-built release for arm64 (Apple silicon) macOS:

```
❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding telmate/proxmox versions matching "2.6.9"...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/telmate/proxmox v2.6.9 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of
│ this provider may have different platforms supported.
╵
```

### PR DESCRIPTION
**Pull request by tagur87**
Updates to go1.16 support and changes to new modules by default
 standards.

 Also due to go1.16 support, adding arm64 support for Darwin/Mac.

 Simplifying the github actions as well to support modules.

Fixes #339 

Also merges latest api code. 
Fixes #338

### CODE REVIEW

**Comment by tagur87** [comment]
@ggongaware @pgporada - Hope this is ok to update to go1.16 with native go module support and simplification. 

I tested a local build of the provider with go1.16, and it worked well. Some of the ACC tests did not work properly, so i wasn't able to verify those. 

Let me know if you have any questions or issues you find.

**Comment by pgporada** [comment]
I have a similar PR open at https://github.com/Telmate/terraform-provider-proxmox/pull/336, but I didn't add any support for Darwin or Mac like you did.

**Comment by tagur87** [comment]
> I have a similar PR open at #336, but I didn't add any support for Darwin or Mac like you did.
Sorry I totally didn't see your PR. 

In this MR I also cleaned up some of the go dep stuff that doesn't need to be there and switched it to go modules based setup based on other popular terraform providers.

I just pushed a change to hopefully fix the Jenkins job that failed. Feel free to use mine or close and update yours for Darwin support.

**Comment by pgporada** [comment]
I'll drop my PR.

**Comment by mleone87** [comment]
@tagur87 can you rebase this PR on latest code?

**Comment by tagur87** [comment]
> @tagur87 can you rebase this PR on latest code?

It has been rebased and should now be ready for merge.

**Comment by mleone87** [comment]
@ggongaware also for me is good, it can be version 2.7.0

**Pull request merged**
