### PR TITLE
Release lock before attempting to read

### LINKED ISSUE #180: [BUG] vga devices adding additional field (type=serial0 vs serial0)
Hi Guys,

I have found an issue in your module which stops you using cloud-init properly.  The issue is when you add a `vga` definition and assign it to the `type` you want.  The system seems to be adding `type=` before the value.

**tf config snippet**
```
  vga {
    memory = 0
    type   = "serial0"
  }
```

You can seen in the screenshot below in black is what your module added in with the snippet above.

image

```
Serial terminal 0 (type=serial0)
```

This black text should read what is shown in red (changed in UI before server restart manually after tf deploy)

```
Serial terminal 0 (serial0)
```
I have also tested if you set it to `std` it even adds `type=std` and it shouldn't be.  Even if you leave out `vga` its adding in `std` and not using the templates config.

I have looked though the code but I am not a `go` expert or even novice and I can't locate the code/bug which is doing this.

A simple fix would be to just remove this `type=` because none of the settings set by `vga` will work in its current state.

Doing a dump of the configs with `qm config ID` shows the problem.  Below you will see a cloned manually from same template which tf uses and one which your tf module used which doesn't work properly.

**tf created config**
```
root@pve-n01:~# qm config 2761
agent: 1
bios: seabios
boot: c
bootdisk: virtio0
cores: 4
cpu: host
description: Kubernetes Nodes
hotplug: network,disk,usb
ide2: lab-vm:vm-2761-cloudinit,media=cdrom,size=4M
ipconfig0: ip=192.168.27.61/24,gw=192.168.27.1
memory: 8192
name: kube-n01
net0: virtio=7E:82:49:4D:0E:5E,bridge=vmbr0
numa: 0
onboot: 1
scsihw: virtio-scsi-pci
serial0: socket
smbios1: uuid=cacde703-b7a1-41a7-9290-ac7a35ff8461
sockets: 4
sshkeys: ********
vga: type=serial0
virtio0: lab-vm:vm-2761-disk-0,format=raw,iothread=1,media=disk,size=123084M
vmgenid: 73f731c5-99a0-40b0-8652-02fc7962125a
```
**Manual created machine via clone in UI**
```
agent: 1,fstrim_cloned_disks=1
balloon: 256
boot: c
bootdisk: virtio0
cores: 2
cpu: host
ide2: prod-vm:vm-100-cloudinit,media=cdrom
ipconfig0: ip=dhcp
memory: 512
name: test-node01
net0: virtio=4A:7C:15:C0:A5:DF,bridge=vmbr0
numa: 0
scsihw: virtio-scsi-pci
serial0: socket
smbios1: uuid=7ef75015-616f-4e71-aec8-840582eda083
sockets: 2
sshkeys: ***************
vga: serial0
virtio0: prod-vm:vm-100-disk-0,size=2252M
vmgenid: 1e1acf36-fef2-48c7-949d-c060c82e7e74
```

I wonder if someone knows or can point me in the right direction in getting this bug squished.

Thank you. 

Kind Regards

### LINKED ISSUE #480: Creating LXC stuck on Still creating... [xxmxxs elapsed]
Terraform is stuck on `Still creating... [xxmxxs elapsed]` while creating LXC, it did create the containers though. The LXC containers seem to be working, I am able to login with the password i supplied in my config. But it looks like Terraform is just stuck.

### main.tf
```

terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
      version = "2.9.4"
    }
  }
}

provider "proxmox" {
  pm_api_url = var.pm_api_url
  pm_api_token_id = var.pm_api_token_id
  pm_api_token_secret = var.pm_api_token_secret
}

resource "proxmox_lxc" "advanced_features" {
  hostname = var.pm_hostname[count.index]
  target_node = var.pm_host_2
  count = var.pm_hostname_count
  start = true
  
  cores = 4
  memory = 2560

  ostemplate   = "local:vztmpl/debian-11-standard_11.0-1_amd64.tar.gz"
  #ostype       = "centos"
  password     = "xxxxx"
  unprivileged = true

  features {
    nesting = true
  }

  rootfs {
    storage = "local-lvm"
    size    = "8G"
  }

  network {
    name   = "eth0"
    bridge = "vmbr0"
    ip     = "dhcp"
    ip6    = "auto"
    hwaddr = var.pm_network_macaddr[count.index]
  }

  mountpoint {
    key = "1"
    slot = 1
    storage = "local-lvm"
    mp      = "/mnt/container/nfs"
    size    = "10G"
  }
}
```

### variables.tf 
```

variable "pm_api_url" {
    description = "PVE management URL"
    default = "https://xxxx:8006/api2/json"
}

variable "pm_api_token_id" {
    description = "Proxmox API token id"
    default = "xxxx@pam!xxx"
}

variable "pm_api_token_secret" {
    description = "Proxmox API secret token"
    default = "xxx"
}

variable "pm_hostname" {
    description = "VM name according to https://namingschemes.com/Greek_Gods"
    type = list(string)
    default = ["xxx", "xxx", "xxx", "xxx"]
}

variable "pm_hostname_count" {
    description = "Amount of VM's"
    default = 4
}

variable "pm_host_1" {
    description = "PVE Host xxx"
    default = "xxx"
}

variable "pm_host_2" {
    description = "PVE Host xxx"
    default = "xxx"
}

variable "pm_network_macaddr" {
    description = "Override the randomly generated MAC Address for the VM."
    default = ["fe:73:42:82:8f:6b","7a:95:f1:1d:87:79","2a:46:af:b2:90:5b","0e:f6:4d:db:24:a8"]
}
```

**Tested on Windows and Debian**

### PR DESCRIPTION
**Pull request by h0tw1r3**
Fixes #480

### CODE REVIEW

**Comment by mleone87** [comment]
correct, but 
`defer lock.unlock()`
at the beginning of create and update function should be unnecessary(as per qemu counterpart), can you add that?

**Comment by h0tw1r3** [comment]
> correct, but `defer lock.unlock()` at the beginning of create and update function should be unnecessary(as per qemu counterpart), can you add that?

Isn't it still necessary because of the return statements throughout the function?

**Comment by mleone87** [comment]
defer is for releasing the lock as soon as the functions returns, but if you releasing the lock manually it is useless

**Comment by h0tw1r3** [comment]
> defer is for releasing the lock as soon as the functions returns, but if you releasing the lock manually it is useless

I would agree, but there are 2 other return statements in this function. If defer is removed, wouldn't an explicit unlock need to be added before those return statements also?

**Pull request merged**
