### PR TITLE
feat: add http_headers, add hostpci resource

### PR DESCRIPTION
**Pull request by BenediktBertsch**
Hey @mleone87,

I've tried to implement the new http_headers and also my previous PR for hostpci, but it seems like that adding hostpci devices is not working. In the tfstate is the hostpci existing, but not on the host.

created vm with hostpci:
image

tfstate:
```
            "hostpci": [
              {
                "host": "0000:01:00.1",
                "rombar": 0
              }
            ],
```

Using normal json with the proxmox api works, but not my implementation. Have I missed some other settings which have to be set?

### CODE REVIEW

**Comment by mleone87** [comment]
let me check your PR locally and see! nice work btw!

**Comment by mleone87** [comment]
@BenediktBertsch pull latest api and this now should work

**Comment by BenediktBertsch** [comment]
@mleone87 thanks for fixing this issue in proxmox-api! Looks good and works locally.

**Comment by brutesque** [comment]
I'm trying to implement this. Do you have an example configuration?

**Pull request merged**
