### PR TITLE
Update `cloud-init` for proxmox-api-go #339

### LINKED ISSUE #997: Cannot set "Upgrade packages" to "No" because of missing property
Proxmox 8.1.10 has an "Upgrade packages" item in "Cloud-init" config.
Upgrade packages item
Upgrade packages dialog

But I can't turn it off via terraform. My `.tf` file:
```hcl
terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "3.0.1-rc1"
    }
  }
}

provider "proxmox" {
  pm_api_url          = var.pm_api_url
  pm_api_token_id     = var.pm_api_token_id
  pm_api_token_secret = var.pm_api_token_secret
}

# ... omitted ...

locals {
  ipconfigs = {
    for i, network in var.networks :
    "ipconfig${i}" => network.ipconfig
    if network.ipconfig != null
  }
}

resource "proxmox_vm_qemu" "pve_vm" {
  name        = var.vm_name
  target_node = var.node
  desc        = var.description
  clone       = var.clone_from
  sockets     = var.cpu_sockets
  cores       = var.cpu_cores
  memory      = var.ram_size
  os_type     = var.provisioning_type
  qemu_os     = var.qemu_os_type
  vmid        = var.vm_id
  scsihw      = var.scsi_hw
  agent       = var.qemu_ga_enabled ? 1 : 0
  full_clone  = var.do_full_clone
  tags        = var.tags
  boot        = "order=${var.boot_order}"
  ciuser      = var.default_user_name
  cipassword  = var.default_user_password
  sshkeys     = (
    length(var.default_user_ssh_pubkeys) > 0
    ? join("\n", var.default_user_ssh_pubkeys)
    : null
  )
  nameserver   = var.dns_config.nameserver
  searchdomain = var.dns_config.search
  ipconfig0    = lookup(local.ipconfigs, "ipconfig0", null)
  ipconfig1    = lookup(local.ipconfigs, "ipconfig1", null)
  ipconfig2    = lookup(local.ipconfigs, "ipconfig2", null)
  ipconfig3    = lookup(local.ipconfigs, "ipconfig3", null)
  dynamic "network" {
    for_each = var.networks
    content {
      model  = "virtio"
      bridge = network.value.bridge
    }
  }
  disks {
    scsi {
      scsi0 {
        disk {
          size    = var.disk_size
          storage = var.disk_storage
          backup  = var.disk_do_backup
        }
      }
    }
  }
  serial {
    id   = 0
    type = "socket"
  }
  vga {
    type = "serial0"
  }
  cloudinit_cdrom_storage = "local-lvm"
}
```

It would be nice to add a `ciupgrade` or something similar to turn on/off auto upgrading packages on boot.

### LINKED ISSUE #1011: Creating a VM using cicustom with network= triggers warning
When I create VMs using `cicustom = "network=storage/whatever.yaml"` I get a warning saying that I'm not assigning a static IP or using DHCP.

Could the code to trigger this warning either check to see if `cicustom` contains a `network=` or be made optionally silent? In my case, networking _is_ configured and this warning represents a false positive.

For reference, the code in question is here:
https://github.com/Telmate/terraform-provider-proxmox/blob/263e663cc4389bae339309bc110650e709b11d09/proxmox/resource_vm_qemu.go#L1922

Thanks!

Edit: I also want to thank you for all the work on this module. Maintaining a project like this can often feel like a thankless task, but I am ever so grateful for it. Thank you!

### LINKED ISSUE #1042: Network parameters cannot be removed from cloudinit settings
System details:

- Proxmox VE 8.2.2
- Terraform v1.8.4
- terraform-provider-proxmox v3.0.1-rc3

Affected cloudinit network parameters:

- `searchdomain`
- `nameserver`
- `ipconfig0-15`

Creating new resources works as expected, mentioned cloudinit network parameters are correctly created.

These parameters can be changed by provider.

Unfortunately, it is not possible to remove these parameters by provider.

By removing the `searchdomain` and `nameserver` arguments from the config, provider ignores this change and does not take any action with the output: `No changes. Your infrastructure matches the configuration.`

By removing `ipconfig0-15`, provider tries to remove this, but after apply the previously created `ipconfig` it still exists. When I try to run terraform apply again, it tries to remove this again and again with no success. The similar situation is with network device removing - https://github.com/Telmate/terraform-provider-proxmox/issues/1027.

These parameters can only be removed through the Proxmox GUI.

### PR DESCRIPTION
**Pull request by Tinyblargon**
Makes terraform compatible with https://github.com/Telmate/proxmox-api-go/pull/339.

Add `ciupgrade` property.  (required work upstream)
fixes #997 (Tested)

When `network` is set in `cicustom` we continue with trying to get the ip.  (required work upstream)
fixes #1011

`searchdomain`, `nameserver`, `ipconfig0-15` can now be removed. (required work upstream)
fixes #1042 (Tested)

### CODE REVIEW

**Comment by Tinyblargon** [comment]
Currently broken for PVE versions lower than 8.0.0 https://github.com/Telmate/proxmox-api-go/issues/344

**Comment by JosBritton** [comment]
Very much looking forward to this

**Comment by maksimsamt** [comment]
@Tinyblargon,
Maybe it makes sense to release this change in rc4?

**Comment by gbrackley** [comment]
@Tinyblargon I'm getting the following warning with v3.0.1-rc4:
```
╷
│ Warning: Cloud-init is enabled but no IP config is set
│
│   with module.flatcar_sample.proxmox_vm_qemu.proxmox_flatcar_vm[0],
│   on ..\..\main.tf line 73, in resource "proxmox_vm_qemu" "proxmox_flatcar_vm":
│   73: resource "proxmox_vm_qemu" "proxmox_flatcar_vm" {
│
│ Cloud-init is enabled in your configuration but no static IP address is set, nor is the DHCP option enabled
╵
```
I have a configuration that does have a network configuration, but **no** cloud-init (I'm using ignition/butane).

Looking at the code, it appear that the warning is in response to a cloud-init without a network configuration. The abridged code reads:
```
    if config.CloudInit != nil {
		... < various other stuff deleted> ...
				return primaryIPs{}, diag.Diagnostics{diag.Diagnostic{
					Severity: diag.Warning,
					Summary:  "Cloud-init is enabled but no IP config is set",
					Detail:   "Cloud-init is enabled in your configuration but no static IP address is set, nor is the DHCP option enabled"}}
			}
		}
	}
```
The new code for initialising  `conf.CloudInit` reads:
```
CloudInit:      mapToSDK_CloudInit(d),
```

The function `mapToSDK_CloudInit` doesn't seem to have a code path that returns nil.  This means the warning will be reported regardless of there is a cloud-init configured.  Am I missing something? Is this by design?

**Comment by gbrackley** [comment]
> There is a cloud-init disk. 

This is the condition I am unclear on. As mentioned above, I don't have a cloud-init disk referenced by the VM.  Looking at the tfstate and the vm configuration (below), I can see that `cipassword` is being round tripped to a non-empty value (but not set by me) - I'm assuming that an empty string is being `crypt`ed.

What is it in this configuration that says there is a cloud-init disk? I am reluctant to falsely call _bug_, but it looks like the function to map the configuration doesn't take into account that there is no cloud-init and returns an empty cloud-init rather than a `nil` cloud init. The warning code looks for a `nil` cloud-init rather than an empty cloud-init.


# tfstate partial

```
 "attributes": {
            "additional_wait": 5,
            "agent": 1,
            "agent_timeout": null,
            "args": "-fw_cfg name=opt/org.flatcar-linux/config,file=/etc/pve/local/ignition/990.ign",
            "automatic_reboot": true,
            "balloon": 0,
            "bios": "ovmf",
            "boot": "order=scsi0",
            "bootdisk": "",
            "ci_wait": null,
            "cicustom": null,
            "cipassword": "",
            "ciupgrade": false,
            "ciuser": "",
            "clone": "flatcar-production-qemu-stable-3815.2.2",
            "clone_wait": 0,
            "cores": 2,
            "cpu": "host",
```

# example vm config

/etc/pve/local/qemu-server/990.cfg

```
#An example **Flatcar** Linux VM provisioned using Terraform.
#
#
#A VM provisioned with Terraform from template flatcar-production-qemu-stable-3815.2.2 on 2024-09-02T07%3A20%3A36Z
#
### Configuration
#
#```
#hook-script%3A local%3Asnippets/cloudinit-to-ignition
#cloud-init%3A local%3Aiso/tf-ci-flatcar-terraform.example.com.iso
#```
agent: 1
args: -fw_cfg name=opt/org.flatcar-linux/config,file=/etc/pve/local/ignition/990.ign
balloon: 0
bios: ovmf
boot: order=scsi0
cicustom:
cipassword: $5$HZnpXPaJ$9pQx4StDbUZQb1VHh1UBAARYSenktKfUxIVw77Y5yZ.
ciupgrade: 0
cores: 2
cpu: host
efidisk0: local:903/base-903-disk-0.raw/990/vm-990-disk-0.qcow2,efitype=4m,pre-enrolled-keys=1,size=128K
hookscript: local:snippets/multi-hookscript.pl
hotplug: network,disk,usb
kvm: 1
memory: 1024
meta: creation-qemu=8.0.2,ctime=1716094446
name: flatcar-terraform.example.com
net0: virtio=00:cd:83:00:7b:c0,bridge=vmbr0,tag=109
numa: 0
onboot: 1
ostype: l26
protection: 0
scsi0: local:990/vm-990-disk-2.raw,replicate=0,size=8694M
scsihw: virtio-scsi-single
serial0: socket
smbios1: uuid=768b2424-7d77-4c93-a722-a4e2e2bd675e
sockets: 1
sshkeys: %0A
startup: order=999
tablet: 1
tags: example;flatcar;terraform
vmgenid: e71bc271-bd7c-4c00-8909-e29c12a12f74
```

**Pull request merged**
