### PR TITLE
Bugfix/require recent module

### PR DESCRIPTION
**Pull request by MaartendeKruijf**
Tiny fix to allow for building the provider again.

### CODE REVIEW

**Comment by mleone87** [comment]
@MaartendeKruijf an update of the go modules and we are ready I think?

**Comment by MaartendeKruijf** [comment]
@mleone87 I've updated the branch. On a side note I could also help maintain the provider if that is of some interest to you?

**Comment by mleone87** [comment]
@MaartendeKruijf thanks! Any help is appreciated

**Comment by MaartendeKruijf** [comment]
@mleone87 could you remove the email from the commit message?

**Pull request merged**
