### PR TITLE
resource_vm_qemu: allow . (dot) in name of virtual machine

### LINKED ISSUE #885: Allow usage of dot (`.`) in virtual machine names
Since #858, it is no longer possible to use `.` in the name of a VM. I usually name my virtual machines to the FQDN of the virtual machine, like `vm1.example.com`, which is no longer possible with this module. I propose to allow `.` in the name (see the PR I've created, #886).

I haven't found anything in the Proxmox documentation that would hint that is not allowed to use `.` in the name of the VM. Please let me know if this is incorrect.

### PR DESCRIPTION
**Pull request by vilhelmprytz**
fixes #885

### CODE REVIEW

**Comment by mleone87** [comment]
@vilhelmprytz thanks for you PR but it's not how regex works, in fact also the actual regex is totally broken

**Comment by vilhelmprytz** [comment]
> @vilhelmprytz thanks for you PR but it's not how regex works, in fact also the actual regex is totally broken

@mleone87 Can you please clarify? I believe the regex itself is correct, but I don't know about the specific Go implementation.

**Comment by mleone87** [comment]
@vilhelmprytz have you tested this regex?

**Comment by vilhelmprytz** [comment]
@mleone87 Yes, I have!

**Pull request merged**
