### PR TITLE
feat: Add 'import-from' parameter to qemu

### PR DESCRIPTION
**Pull request by jamesharr**
I think this addresses #605. It adds an optional `import-disk` parameter for VMs.

I have no idea how to test this, or if I'm getting the additions made in the correct place. Please review with scrutiny and/or modify as-needed.

### CODE REVIEW

**Comment by mleone87** [comment]
This feature should be used in the next version of the provider for sure!

However, I feel that putting this in the resource properties would cause a lot of problem, this is not a parameter to be passed to the API every time we make a change(just an example).
The proxmox developers thought of it as a one-time pass parameter so it should be used only in resource creation(or recreation)

**Comment by jamesharr** [comment]
Ty. I agree with that assessment. For now, we're cloning from a template VM, but I would like to use this in the future.

I might need some pointers on how to accomplish this... I have limited experience using this TF provider let alone developing a TF provider, so I'm kind of lost with how to only apply that parameter on initial creation. I'll poke around today a bit but I'm not sure how far I'll get.

One other thing I noticed is that this might be an alternative to using iso or clone on the VM. When importing a disk image, neither parameter is needed. At the moment, one of those options is required, so I think this patch needs to add something to allow for a 3rd option instead of import/iso.

**Comment by jamesharr** [comment]
I have a local development environment going. I found another issue that we'll run into, specifically that I want to use cloud-init without cloning from an existing template.

```
proxmox_vm_qemu.control-node: Creating...
╷
│ Error: cloud-init parameters only supported on clones or updates
│ 
│   with proxmox_vm_qemu.control-node,
│   on main.tf line 93, in resource "proxmox_vm_qemu" "control-node":
│   93: resource "proxmox_vm_qemu" "control-node" {
│ 
╵
Command failed 1
```

I'm going to modify the PR text to include more details of my proposed use-case since this is turning into a bigger thing than just adding a parameter. That way, I'll have something to work from.

**Comment by myplixa** [comment]
Hi guys, can you tell me when will be the release of this feature?

**Comment by TomyLobo** [comment]
@Tinyblargon this change didn't survive the transition to 3.x.
It was removed in https://github.com/Telmate/terraform-provider-proxmox/pull/926/commits/5b89c2ea9c23b7dfbbcb047157f6679b1631d656#diff-104365919f693375882979581d9f36f5266991eef361948e56c220931fe886ddL600 and never re-added.

Is it possible to add this back?
It's really useful in order to import official disk images.

**Pull request merged**
