### PR TITLE
feat: overhaul qemu disks implementation

### PR DESCRIPTION
**Pull request by Tinyblargon**
This is #889 with the mentioned bug fixes applied.
Again thanks to @hestiahacker for the rebase.

Continuation of #794

This should solve: #887
Have done some limited testing and didn't encounter any issues.

### CODE REVIEW

**Comment by Tinyblargon** [comment]
@MaartendeKruijf could you take a look at the rebase? This is the first time I had to work across forks.

**Comment by evan-a-a** [comment]
This change doesn't handle non-IDE cloudinit drives properly. In Proxmox it's valid to have a cloudinit drive attached as IDE, SATA, or SCSI. The original implementation of disk management has handling for cloudinit drives attached using various storage types, and this needs to be accounted for here.

Additionally, reserving ide2 for cdrom is inflexible. It's perfectly valid for ide2 NOT to be a cdrom drive, so the provider should account for all cases.

**Comment by ihatethecloud** [comment]
Doesn't work for me.

```hcl
terraform {
  required_providers {
    proxmox = {
      # source  = "TheGameProfi/proxmox"
      # version = ">= 2.9.14"
      source  = "registry.example.com/telmate/proxmox"
      version = ">=1.0.0"
    }
  }
}

variable "proxmox_api_url" {
  type = string
}

variable "proxmox_api_token_id" {
  type      = string
  sensitive = true
}

variable "proxmox_api_token_secret" {
  type      = string
  sensitive = true
}

provider "proxmox" {
  pm_api_url          = var.proxmox_api_url
  pm_api_token_id     = var.proxmox_api_token_id
  pm_api_token_secret = var.proxmox_api_token_secret
  pm_log_enable       = true
  pm_log_file         = "terraform-plugin-proxmox.log"
  pm_debug            = true
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
  }
}
```

```hcl
resource "proxmox_vm_qemu" "lab_servers" {
  name  = "test-vm-0.home.local"

  target_node = var.proxmox_host
  clone       = var.template_name

  agent    = 1
  os_type  = "cloud-init"
  cores    = 2
  sockets  = 1
  cpu      = "host"
  memory   = 2048
  scsihw   = "virtio-scsi-pci"
  bootdisk = "scsi0"

  disk {
    size    = "18G"
    type    = "scsi"
    storage = "vg_nvme"
    ssd     = 1
  }

  network {
    model  = "virtio"
    bridge = "vmbr0"
  }

  lifecycle {
    ignore_changes = [network]
  }
  
  ipconfig0 = "ip=dhcp"

  sshkeys = <<EOF
  ${var.ssh_key}
  EOF

}
```

```hcl
Terraform will perform the following actions:

  # proxmox_vm_qemu.lab_servers will be created
  + resource "proxmox_vm_qemu" "lab_servers" {
      + additional_wait           = 5
      + agent                     = 1
      + automatic_reboot          = true
      + balloon                   = 0
      + bios                      = "seabios"
      + boot                      = (known after apply)
      + bootdisk                  = "scsi0"
      + clone                     = "RL92-Template"
      + clone_wait                = 10
      + cores                     = 2
      + cpu                       = "host"
      + default_ipv4_address      = (known after apply)
      + define_connection_info    = true
      + force_create              = false
      + full_clone                = true
      + guest_agent_ready_timeout = 100
      + hotplug                   = "network,disk,usb"
      + id                        = (known after apply)
      + ipconfig0                 = "ip=dhcp"
      + kvm                       = true
      + memory                    = 2048
      + name                      = "test-vm-0.home.local"
      + nameserver                = (known after apply)
      + onboot                    = false
      + oncreate                  = false
      + os_type                   = "cloud-init"
      + preprovision              = true
      + reboot_required           = (known after apply)
      + scsihw                    = "virtio-scsi-pci"
      + searchdomain              = (known after apply)
      + sockets                   = 1
      + ssh_host                  = (known after apply)
      + ssh_port                  = (known after apply)
      + sshkeys                   = <<-EOT
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJEvp+CSY962e6pqAnmANY56tiL8q7Xvy6C8sseAr1obcW4kct2/KbAi11d/Wseav+vS5B08euHl/wfg0wQE63G+BL7W1vVZhjm06cB4GFayE2UDuBiQpg16R6f+tUAHejz4J3XgWBrb3Pdxh4h/E3Zt6DLaodtUb+jZy2eUc1M7AidAUCKOGCZhdK8626E4tSnVD1ySlZSkrTXSX/p0ESn4wwZVuv6QWsOOigUuImL62evtXg+6ve9Zx8gxIOGxQn0FZAR5qsxQHnF0uumM9kdhoEHJlnORw+FNEJ8ynAKmmkWfTKooZ6HCXi0X8fFAeh5MT/TyLlSPbTNIKBMdlyLI351x5fwyMwER18hCD/ljLLUaL36FWqn282Bkt8qS8rJAdC41Q/D4E0WcO4WW7FhX5bF73hl3bL5RVKoRDfxoiMugfBdU/INKYuyMU2YGVaaLQW7VecD3kXXZcvr40DAqAZ0bPPq5y3o0efOO7R/Xbdoq17o5x+GB9kdfX5I5s=
        EOT
      + tablet                    = true
      + target_node               = "artemis"
      + unused_disk               = (known after apply)
      + vcpus                     = 0
      + vlan                      = -1
      + vm_state                  = "running"
      + vmid                      = (known after apply)

      + disk {
          + backup             = true
          + cache              = "none"
          + file               = (known after apply)
          + format             = (known after apply)
          + iops               = 0
          + iops_max           = 0
          + iops_max_length    = 0
          + iops_rd            = 0
          + iops_rd_max        = 0
          + iops_rd_max_length = 0
          + iops_wr            = 0
          + iops_wr_max        = 0
          + iops_wr_max_length = 0
          + iothread           = 0
          + mbps               = 0
          + mbps_rd            = 0
          + mbps_rd_max        = 0
          + mbps_wr            = 0
          + mbps_wr_max        = 0
          + media              = (known after apply)
          + replicate          = 0
          + size               = "18G"
          + slot               = (known after apply)
          + ssd                = 1
          + storage            = "vg_nvme"
          + storage_type       = (known after apply)
          + type               = "scsi"
          + volume             = (known after apply)
        }

      + network {
          + bridge    = "vmbr0"
          + firewall  = false
          + link_down = false
          + macaddr   = (known after apply)
          + model     = "virtio"
          + queues    = (known after apply)
          + rate      = (known after apply)
          + tag       = -1
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Screenshot 2024-01-07 at 17 18 34

I can't explain but.... it worked once. Template has an 8gb disk and the plugin didn't resize it to 18.

**Comment by Tinyblargon** [comment]
@ihatethecloud 

This update deprecates the `disk: {}` block as it is unreliable.

Could you try the following syntax for the disks:
```hcl
resource "proxmox_vm_qemu" "lab_servers" {
//<arguments omitted for brevity...>
  disks {
    scsi {
      scsi0 {
        disk {
          size = 18
          storage = "vg_nvme"
          emulatessd = true
        }
      }
    }
  }
//<arguments omitted for brevity...>
}
```

**Comment by ihatethecloud** [comment]
```shell
➜  terraform-provider-proxmox git:(master) git remote -v
origin	https://github.com/Tinyblargon/terraform-provider-proxmox.git (fetch)
origin	https://github.com/Tinyblargon/terraform-provider-proxmox.git (push)
➜  terraform-provider-proxmox git:(master) make
 -> Building
mkdir -p bin
CGO_ENABLED=0 go build -trimpath -o bin/terraform-provider-proxmox
Built terraform-provider-proxmox

➜  terraform-provider-proxmox git:(master) cp bin/terraform-provider-proxmox ~/.terraform.d/plugins/registry.example.com/telmate/proxmox/1.0.0/darwin_arm64/terraform-provider-proxmox

➜  general-infrastructure git:(main) ✗ cd ../general-infrastructure

➜  general-infrastructure git:(main) ✗ terraform version
Terraform v1.6.6
on darwin_arm64
+ provider registry.example.com/telmate/proxmox v1.0.0

➜  general-infrastructure git:(main) ✗ terraform plan
╷
│ Error: Unsupported block type
│
│   on main.tf line 18, in resource "proxmox_vm_qemu" "lab_servers":
│   18:   disks {
│
│ Blocks of type "disks" are not expected here. Did you mean "disk"?
╵
```


```hcl
resource "proxmox_vm_qemu" "lab_servers" {
  name = "test-vm-0.home.local"

  target_node = var.proxmox_host
  clone       = var.template_name

  vmid = 666

  agent    = 1
  os_type  = "cloud-init"
  cores    = 2
  sockets  = 1
  cpu      = "host"
  memory   = 2048
  scsihw   = "virtio-scsi-pci"
  bootdisk = "scsi0"

  disks {
    scsi {
      scsi0 {
        disk {
          size       = 18
          storage    = "vg_nvme"
          emulatessd = true
        }
      }
    }
  }

  network {
    model  = "virtio"
    bridge = "vmbr0"
  }

  lifecycle {
    ignore_changes = [network]
  }

  ipconfig0 = "ip=dhcp"

  sshkeys = <<EOF
  ${var.ssh_key}
  EOF

}
```

Hopefully my mac is not the problem here.

**Comment by Tinyblargon** [comment]
@ihatethecloud did you localy build the branch of this PR?

Here the instructions for building localy are explained: https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1878134269

**Comment by ihatethecloud** [comment]
@Tinyblargon aaahhh darn. I forgot to checkout the branch. As always the problem is between the chair and the computer.
Anyway. It worked fine now the machine booted only thing I noticed at first glance is the fact that the disk is the same size as the template's disk, 8gb. Has not been resized to 18Gb.

```hcl
     + disks {
          + scsi {
              + scsi0 {
                  + disk {
                      + backup               = true
                      + emulatessd           = true
                      + format               = "raw"
                      + id                   = (known after apply)
                      + iops_r_burst         = 0
                      + iops_r_burst_length  = 0
                      + iops_r_concurrent    = 0
                      + iops_wr_burst        = 0
                      + iops_wr_burst_length = 0
                      + iops_wr_concurrent   = 0
                      + linked_disk_id       = (known after apply)
                      + mbps_r_burst         = 0
                      + mbps_r_concurrent    = 0
                      + mbps_wr_burst        = 0
                      + mbps_wr_concurrent   = 0
                      + size                 = 18
                      + storage              = "vg_nvme"
                    }
                }
            }
        }
```

Screenshot 2024-01-07 at 19 05 35

**Comment by ihatethecloud** [comment]
Interesting. Running terraform plan again produces

```
 ~ resource "proxmox_vm_qemu" "lab_servers" {
      + bootdisk                  = "scsi0"
      - desc                      = "Rocky Linux 9.2 Template" -> null
        id                        = "artemis/qemu/666"
        name                      = "test-vm-0.home.local"
      - qemu_os                   = "l26" -> null
        # (38 unchanged attributes hidden)

      ~ disks {
          - ide {
            }
          ~ scsi {
              ~ scsi0 {
                  ~ disk {
                      ~ backup               = false -> true
                      ~ emulatessd           = false -> true
                      + format               = "raw"
                        id                   = 0
                      - replicate            = true -> null
                      ~ size                 = 8 -> 18
                        # (15 unchanged attributes hidden)
                    }
                }
            }
        }

        # (2 unchanged blocks hidden)
    }
```

**Comment by hestiahacker** [comment]
I can reproduce this issue with the disk not being resized. I didn't notice before, but after deploying the first time, the disk is the same size as the template (10G) instead of the size specified (20G). This is a test using [my small example terraform](https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1873548314) I posted to the ticket.

When I tried to apply again, it noticed that the disk size needed changed (same as reported above), and thought it should wipe out a bunch of fields. Since it's a test VM, I decided to play the "lets see what happens" card and the answer was that it failed to apply the changes.

```
  # proxmox_vm_qemu.server will be updated in-place
  ~ resource "proxmox_vm_qemu" "server" {
      + bootdisk                  = "virtio0"
      - desc                      = "Debian 12, generated on 2023-12-18T22:42:33Z" -> null
        id                        = "ra/qemu/101"
        name                      = "test.example.com"
      - qemu_os                   = "other" -> null
        # (35 unchanged attributes hidden)

      ~ disks {
          - ide {
              - ide0 {
                  - disk {
                      - backup               = true -> null
                      - discard              = false -> null
                      - emulatessd           = false -> null
                      - id                   = 0 -> null
                      - iops_r_burst         = 0 -> null
                      - iops_r_burst_length  = 0 -> null
                      - iops_r_concurrent    = 0 -> null
                      - iops_wr_burst        = 0 -> null
                      - iops_wr_burst_length = 0 -> null
                      - iops_wr_concurrent   = 0 -> null
                      - linked_disk_id       = -1 -> null
                      - mbps_r_burst         = 0 -> null
                      - mbps_r_concurrent    = 0 -> null
                      - mbps_wr_burst        = 0 -> null
                      - mbps_wr_concurrent   = 0 -> null
                      - replicate            = true -> null
                      - size                 = 0 -> null
                      - storage              = "local-zfs" -> null
                    }
                }
            }
          ~ virtio {
              ~ virtio0 {
                  ~ disk {
                        id                   = 0
                      - replicate            = true -> null
                      ~ size                 = 10 -> 20
                      ~ storage              = "local" -> "local-zfs"
                        # (17 unchanged attributes hidden)
                    }
                }
            }
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
```

And when trying to apply the change...

```
│ Error: error updating VM: 500 unable to parse zfs volume name '101/vm-101-disk-0.raw', error status: {"data":null} (params: map[bios:seabios boot:order=virtio0;ide2;net0 cores:1 cpu:host delete:ide0 hotplug:network,disk,usb ipconfig0:ip=192.168.22.222/22,gw=192.168.22.1 kvm:true memory:512 name:test.example.com nameserver:192.168.22.100 192.168.23.100 net0:virtio=0A:6F:BE:38:71:A4,bridge=vmbr0 numa:false onboot:false scsihw:virtio-scsi-pci smbios1:uuid=b7df731d-e5b6-49da-a6da-bae13ff85d98 sockets:1 sshkeys:REDACTED tablet:true virtio0:local-zfs:101/vm-101-disk-0.raw,cache=writeback,replicate=0 vmid:101])
│ 
│   with proxmox_vm_qemu.server,
│   on minimal.tf line 14, in resource "proxmox_vm_qemu" "server":
│   14: resource "proxmox_vm_qemu" "server" {
│ 
```

It doesn't look like a very difficult volume name to parse, but if it's trying to update the "storage" field to "null", I could imagine how that might be a problem. :joy: The error status is not helpful, but I'm not sure if we can do anything about that in this case.

**Comment by ihatethecloud** [comment]
I have something else.

```
Plan: 0 to add, 1 to change, 0 to destroy.
proxmox_vm_qemu.lab_servers: Modifying... [id=artemis/qemu/666]
╷
│ Error: 500 you can't move to the same storage with same format
│
│   with proxmox_vm_qemu.lab_servers,
│   on main.tf line 1, in resource "proxmox_vm_qemu" "lab_servers":
│    1: resource "proxmox_vm_qemu" "lab_servers" {
│
|
```

**Comment by Tchoupinax** [comment]
Hey @Tinyblargon,

As note, I come from [here](https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1879660716)
I tested your patch and it works well !

You patch requires quite breaking changes (thanks for the template you provided in the issue).

image

Then, it works well. It fixed my issues:

- [x] Disk size is 10G, which is the size of the template. It should have been overridden (it worked before)
- [x] There is no cloud init drive
- [x] Hard disk has additional parameters which did not have before

The new way to declare disks is quite intuitive, I like it! Thank your for your work!

**Comment by Tchoupinax** [comment]
However, I got this issue when I want to rename the VM

```  # module.node_1.proxmox_vm_qemu.vm will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm" {
      + cloudinit_cdrom_storage   = "local-lvm"
        id                        = "pve/qemu/104"
      ~ name                      = "node-2" -> "node-1"
        # (39 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }```

```
│ Error: error updating VM: 500 lvcreate 'pve/vm-104-cloudinit' error:   Logical Volume "vm-104-cloudinit" already exists in volume group "pve", error status: {"data":null} (params: map[agent:1 bios:seabios boot:c disk,usb ide3:local-lvm:cloudinit,format=raw ipconfig0:ip=dhcp kvm:true name:node-1 scsihw:virtio-scsi-pci smbios1tablet:true vmid:104])
```
(I removed some information from the log)

**Comment by Tinyblargon** [comment]
@Tchoupinax found the issue causing the `Error: error updating VM: 500 lvcreate 'pve/vm-104-cloudinit' error:`

https://github.com/Telmate/proxmox-api-go/pull/294 is the fix.

To use it now, you would have to rebuild the terraform provider with the `proxmox-go-api` dependency replaced.
This commit explains how: https://github.com/Telmate/terraform-provider-proxmox/pull/890/files#diff-1edfb41c789b8ac0a99efa6714b6ed0c09d26ea2edea7dd7db5fa0d45c9b125e.

**Comment by MaartendeKruijf** [comment]
@Tinyblargon it looks like the rebase worked out, or do you need help with that still?

**Comment by hestiahacker** [comment]
@Tinyblargon I recompiled using 50da04d7dc4591a78fff860a1d511616c30702cb of the provider and 1f4b2a3cd39ef02324e54e4818099a691c60a04a of the proxmox-api-go library. The only local change that I made was to add the `replace` directive in go.mod to use a local directory instead of the github version of the repo.

These versions **did not fix** the error that as I was able to [repro earlier](https://github.com/Telmate/terraform-provider-proxmox/pull/892#issuecomment-1880134279) with the disk being the wrong size on the first deployment.

However, these versions **did fix** the "500 unable to parse zfs volume name '101/vm-101-disk-0.raw'" error and doing a second apply did make the disk go from 10G (the size of the template I'm cloning) to 20G (the size specified in my terraform file).

In my opinion, this MR is ready to be merged into the default branch and if I can still repro the "disk wrong size on initial deploy" problem, I can open a new issue about that.

**Side note**: The instructions for using a local checkout of the proxmox-api-go repo that I added were incorrect, but I've now fixed them and they're still in the queue to be merged.

**Review by Tunechi2323 — APPROVED** [review]

**Comment by mleone87** [comment]
safe to merge then?

**Comment by Tinyblargon** [comment]
@mleone87 All the issues that were with this PR had to be fixed upstream. The logic for converting from terraform to proxmox-api-go is good. Might still run into some upstream bugs when people are gonna be using this.
Can we maybe make a release candidate build?

Before this gets merged, I'd like to update the go.mod file to include the latest version of proxmox-go-api. And add some more debug statements. I think the issue @hestiahacker described is that the vm isn't updated after it was cloned. I'd like to figure out which code path it is taking.

**Comment by Tinyblargon** [comment]
@hestiahacker could you test if the disk get resized on create with debug enabled, it should print the following `[DEBUG][QemuVmCreate] update VM after clone`?

**Comment by ihatethecloud** [comment]
Here is my test.
Note: Template has an 8gb disk

```hcl
resource "proxmox_vm_qemu" "lab_servers" {
  name = "test-vm-0.home.local"

  target_node = var.proxmox_host
  clone       = var.template_name

  vmid = 666

  agent    = 1
  os_type  = "cloud-init"
  cores    = 2
  sockets  = 1
  cpu      = "host"
  memory   = 2048
  scsihw   = "virtio-scsi-pci"
  bootdisk = "scsi0"

  disks {
    scsi {
      scsi0 {
        disk {
          size       = 18
          storage    = "vg_nvme"
          emulatessd = true
        }
      }
    }
  }

  network {
    model  = "virtio"
    bridge = "vmbr0"
  }

  lifecycle {
    ignore_changes = [network]
  }

  ipconfig0 = "ip=dhcp"

  sshkeys = <<EOF
  ${var.ssh_key}
  EOF

}
```

apply

```
  # proxmox_vm_qemu.lab_servers will be created
  + resource "proxmox_vm_qemu" "lab_servers" {
      + additional_wait           = 5
      + agent                     = 1
      + automatic_reboot          = true
      + balloon                   = 0
      + bios                      = "seabios"
      + boot                      = (known after apply)
      + bootdisk                  = "scsi0"
      + clone                     = "RL92-Template"
      + clone_wait                = 10
      + cores                     = 2
      + cpu                       = "host"
      + default_ipv4_address      = (known after apply)
      + define_connection_info    = true
      + force_create              = false
      + full_clone                = true
      + guest_agent_ready_timeout = 100
      + hotplug                   = "network,disk,usb"
      + id                        = (known after apply)
      + ipconfig0                 = "ip=dhcp"
      + kvm                       = true
      + linked_vmid               = (known after apply)
      + memory                    = 2048
      + name                      = "test-vm-0.home.local"
      + nameserver                = (known after apply)
      + onboot                    = false
      + oncreate                  = false
      + os_type                   = "cloud-init"
      + preprovision              = true
      + reboot_required           = (known after apply)
      + scsihw                    = "virtio-scsi-pci"
      + searchdomain              = (known after apply)
      + sockets                   = 1
      + ssh_host                  = (known after apply)
      + ssh_port                  = (known after apply)
      + sshkeys                   = <<-EOT
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJEvp+CSY962e6pqAnmANY56tiL8q7Xvy6C8sseAr1obcW4kct2/KbAi11d/Wseav+vS5B08euHl/wfg0wQE63G+BL7W1vVZhjm06cB4GFayE2UDuBiQpg16R6f+tUAHejz4J3XgWBrb3Pdxh4h/E3Zt6DLaodtUb+jZy2eUc1M7AidAUCKOGCZhdK8626E4tSnVD1ySlZSkrTXSX/p0ESn4ww123uv6QWsOOigUuImL62evtXg+6ve9Zx8gxIOGxQn0FZAR5qsxQHnF0uumM9kdhoasdw+FNEJ8ynAKmmkWfTKooZ6HCXi0X8fFAeh5MT/TyLlSPbTNIKBMdlyLI351x5fwyMwER18hCD/ljLLUaL36FWqn282Bkt8qS8rJAdC41Q/D4E0WcO4WW7FhX5bF73hl3bL5RVKoRDfxoiMugfBdU/INKYuyMU2YGVaaLQW7VecD3kXXZcvr40DAqAZ0bPPq5y3o0efOO7R/Xbdoq17o5x+GB9kdfX5I5s=
        EOT
      + tablet                    = true
      + target_node               = "artemis"
      + unused_disk               = (known after apply)
      + vcpus                     = 0
      + vlan                      = -1
      + vm_state                  = "running"
      + vmid                      = 666

      + disks {
          + scsi {
              + scsi0 {
                  + disk {
                      + backup               = true
                      + emulatessd           = true
                      + format               = "raw"
                      + id                   = (known after apply)
                      + iops_r_burst         = 0
                      + iops_r_burst_length  = 0
                      + iops_r_concurrent    = 0
                      + iops_wr_burst        = 0
                      + iops_wr_burst_length = 0
                      + iops_wr_concurrent   = 0
                      + linked_disk_id       = (known after apply)
                      + mbps_r_burst         = 0
                      + mbps_r_concurrent    = 0
                      + mbps_wr_burst        = 0
                      + mbps_wr_concurrent   = 0
                      + size                 = 18
                      + storage              = "vg_nvme"
                    }
                }
            }
        }

      + network {
          + bridge    = "vmbr0"
          + firewall  = false
          + link_down = false
          + macaddr   = (known after apply)
          + model     = "virtio"
          + queues    = (known after apply)
          + rate      = (known after apply)
          + tag       = -1
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
proxmox_vm_qemu.lab_servers: Creating...
proxmox_vm_qemu.lab_servers: Still creating... [10s elapsed]
proxmox_vm_qemu.lab_servers: Still creating... [20s elapsed]
proxmox_vm_qemu.lab_servers: Still creating... [30s elapsed]
proxmox_vm_qemu.lab_servers: Still creating... [40s elapsed]
proxmox_vm_qemu.lab_servers: Creation complete after 50s [id=artemis/qemu/666]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Machine booted fine

If I run terrafom plan again I get this

```
proxmox_vm_qemu.lab_servers: Refreshing state... [id=artemis/qemu/666]

Terraform used the selected providers to generate the following execution plan. Resource actions
are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_vm_qemu.lab_servers will be updated in-place
  ~ resource "proxmox_vm_qemu" "lab_servers" {
      + bootdisk                  = "scsi0"
      - desc                      = "Rocky Linux 9.2 Template" -> null
        id                        = "artemis/qemu/666"
        name                      = "test-vm-0.home.local"
      - qemu_os                   = "l26" -> null
        # (38 unchanged attributes hidden)

      ~ disks {
          - ide {
            }
          ~ scsi {
              ~ scsi0 {
                  ~ disk {
                      ~ backup               = false -> true
                      ~ emulatessd           = false -> true
                      + format               = "raw"
                        id                   = 0
                      - replicate            = true -> null
                      ~ size                 = 8 -> 18
                        # (15 unchanged attributes hidden)
                    }
                }
            }
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take
exactly these actions if you run "terraform apply" now.
```

apply returns error

```
Plan: 0 to add, 1 to change, 0 to destroy.
proxmox_vm_qemu.lab_servers: Modifying... [id=artemis/qemu/666]
╷
│ Error: 500 you can't move to the same storage with same format
│
│   with proxmox_vm_qemu.lab_servers,
│   on main.tf line 1, in resource "proxmox_vm_qemu" "lab_servers":
│    1: resource "proxmox_vm_qemu" "lab_servers" {
│
╵
```

**Comment by hestiahacker** [comment]
> @hestiahacker could you test if the disk get resized on create with debug enabled, it should print the following `[DEBUG][QemuVmCreate] update VM after clone`?

I was using the `BugFix-CloudInit` branch of `proxmox-api-go`, which I don't see in your repo anymore. When I try to switch to the `Overhaul-Qemu-Disks-rebased` branch, which looks like where these changes are, I get this error:

```sh
git checkout -t origin/Overhaul-Qemu-Disks-rebased
fatal: 'origin/Overhaul-Qemu-Disks-rebased' is not a commit and a branch 'Overhaul-Qemu-Disks-rebased' cannot be created from it
```

If I delete the working directory that has `BugFix-CloudInit` branch and then clone the repo and check out the `Overhaul-Qemu-Disks-rebased` branch, will it have the fixes from the `BugFix-CloudInit` branch?

Second question, I should be looking for these new print statements in the .log file created when I enable logging [like this](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/index.md#logging), right?

**Comment by mleone87** [comment]
If we are ready to merge and make some more test I would let you @Tinyblargon update the dependencies and merge

Also close the other 2 old PR, right? @hestiahacker and @Tinyblargon

**Comment by hestiahacker** [comment]
Yeah, my MR appears to be a subset of what's in this MR, so I've closed mine.  ty

**Comment by SySamu-Hallon** [comment]
Any new about disk expand on creation? I´m getting the same error. If I apply twice the cloud init drive is getting removed, but the main disk is getting resized.

**Comment by Tinyblargon** [comment]
@SySamu-Hallon the cloud-init disk has to be configured in Terraform (templates only need to have a disk with an os, as Terraform manages everything).

**Comment by Tinyblargon** [comment]
@SySamu-Hallon so the disk is only resized on the second run? Do i understand this correctly?

**Comment by SySamu-Hallon** [comment]
@Tinyblargon Yep, that's correct. I run the apply but the main disk is not being resized, but, if i do a second apply it resizes.

**Comment by Tinyblargon** [comment]
@SySamu-Hallon could you create a separate issue for this? Thank you.

**Pull request merged**
